spring:
    profiles:
        active: development
---
spring:
    profiles: development
    jpa:
        generate-ddl: true
    h2:
        console:
            enabled: true
server:
    port: 8080

spring.output.ansi.enabled: ALWAYS